# NOTE: app icon in ./kitty.app.png, must be max 128x128
# icon source: https://github.com/rose-pine/kitty

# transparency
background_opacity 0.9
# dynamic_background_opacity yes

# blur
background_blur 1

# BEGIN_KITTY_FONTS
font_family      family='Maple Mono' postscript_name=MapleMono-Regular features="+ss03"
bold_font        family='Maple Mono' postscript_name=MapleMono-Bold
italic_font      auto
bold_italic_font family='Maple Mono' postscript_name=MapleMono-BoldItalic
# END_KITTY_FONTS

# Nerd Fonts v3.3.0
# symbol_map U+e000-U+e00a,U+ea60-U+ebeb,U+e0a0-U+e0c8,U+e0ca,U+e0cc-U+e0d7,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b7,U+e700-U+e8ef,U+ed00-U+efc1,U+f000-U+f2ff,U+f000-U+f2e0,U+f300-U+f381,U+f400-U+f533,U+f0001-U+f1af0 Symbols Nerd Font Mono

# reminder: ctrl-shift-[+|-] to zoom in/out =~
font_size 11.0
text_composition_strategy 3 0
disable_ligatures cursor

# disable beep
enable_audio_bell no

# cursor styling
shell_integration no-cursor
cursor_beam_thickness 2.0
cursor_trail 1
cursor_trail_start_threshold 2
cursor_trail_decay 0.1 0.3

# url styling
url_style curly

# move padding to bottom right
placement_strategy top-left

# no confirmation when closing tabs
confirm_os_window_close 0

window_padding_width 4
window_margin_width 4


# BEGIN_KITTY_THEME
# Rosé Pine
include current-theme.conf
# END_KITTY_THEME
